# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Schema Information
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# id         integer     (Autogenerated id)
# user_id    inetger     (shared to this user)
# link_id    integer     (ewarel_id referring to one ewarel)
#
class FriendLinks < ActiveRecord::Base

end